### ISSUE TITLE
CronDebugListener: array_merge(): Expected parameter 1 to be an array, null given

### ISSUE THREAD

**Issue by Biont** [inpsyde/Wonolog#56] opened 2020-09-10 12:10 UTC
#### Version Information

* PHP: 7.2
* WordPress: 5.4.2

#### Description

I am not sure im some actor is misbehaving in the WP setup I am seeing the problem with, but the first entry of `_get_cron_array()` is ` 0 => false ` [when CronDebugListener grabs it](https://github.com/inpsyde/Wonolog/blob/60ee47b0b2040e54fd11327751e69546df5750ee/src/HookListener/CronDebugListener.php#L104)

This causes errors that of course spam the logs when this value is passed into the `array_reduce` callback a little later.

My suggestion would be to run `array_filter( $cron_array )` before passing it on

**Comment by gmazzap** [comment] 2020-09-10 19:40
Nervemind @Biont I should have fixed it with f250c0d 

Can you please confirm requireng `dev-master` the issue is gone?

**Comment by gmazzap** [comment] 2021-11-16 18:37
Closing this considering no feedback from more than 1 year.

The mentioned f250c0d should have fixed it for v1, and v2 will not suffer from it.

**Closed by gmazzap** 2021-11-16 18:37 UTC
Labels: bug
